apiVersion: v1
kind: Service
metadata:
  name: azure-load-balancer
spec:
  loadBalancerIP: 23.96.105.210
  type: LoadBalancer
  ports:
  - port: 9090
  selector:
    app: azure-load-balancer