apiVersion: v1
kind: Service
metadata:
  name: azure-load-balancer
spec:
  loadBalancerIP: <your IP Address>
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-load-balancer