version: "3.8"
services:
  blackbox:
    image: prom/blackbox-exporter:master
    volumes:
      - ./bbconf/:/config
    command:
      - "--config.file=/config/blackbox.yml"
    ports:
      - "9115:9115"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
