---
- name: Elasticsearch with custom configuration
  hosts: centos_vms
  roles:
    - role: elastic.elasticsearch
  vars:
    es_instance_name: "node-01"
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      node.name: "node-01"
      cluster.name: "custom-cluster"
      discovery.zen.ping.unicast.hosts: "localhost:9301"
      http.port: 9201
      transport.tcp.port: 9301
      node.data: false
      node.master: true
      bootstrap.memory_lock: true
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 1g
    es_api_port: 9201
    es_api_basic_auth_username: admin
    es_api_basic_auth_password: changeme